name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  PROJECT_ID: 'incrediforms-api'
  REGION: 'us'
  SERVICE: 'incrediforms-api'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/642822023513/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'incrediforms-sa@incrediforms-api.iam.gserviceaccount.com'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: 'gcr.io'

      - name: 'Build and Push Container'
        run: |
          docker build --platform linux/amd64 -t gcr.io/${{ env.PROJECT_ID }}/api:latest .
          docker push gcr.io/${{ env.PROJECT_ID }}/api:latest

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: 'gcr.io/${{ env.PROJECT_ID }}/api:latest'
          env_vars: |
            NODE_ENV=production
          secrets: |
            DATABASE_URL=db-url-secret:latest

      - name: 'Show output...'
        run: echo ${{ steps.deploy.outputs.url }}
