name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  PROJECT_ID: 'incrediforms-api'
  REGION: 'us-central1'
  SERVICE: 'incrediforms-api'
  SERVICE_ACCOUNT: 'incrediforms-sa@incrediforms-api.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/642822023513/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
  REGISTRY: 'gcr.io'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker Auth'
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: 'Build and Push Container'
        run: |
          docker build --platform linux/amd64 -t gcr.io/${{ env.PROJECT_ID }}/api:latest .
          docker push gcr.io/${{ env.PROJECT_ID }}/api:latest

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: 'gcr.io/${{ env.PROJECT_ID }}/api:latest'
          service_account: '${{ env.SERVICE_ACCOUNT }}'
          env_vars: |
            NODE_ENV=production
          secrets: |
            DATABASE_URL=projects/${{ env.PROJECT_ID }}/secrets/db-url-secret/versions/latest:latest

      - name: 'Show output...'
        run: echo ${{ steps.deploy.outputs.url }}
